# Generated by Django 2.2.3 on 2019-07-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uuid',
            field=models.CharField(max_length=150),
        ),
    ]
