# Generated by Django 2.2.3 on 2019-07-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190711_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='original_image',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='task',
            name='sized_image',
            field=models.CharField(max_length=150),
        ),
    ]
